run:
  name: all
  prefix: batch_1407
  scenarios:
    enable: true
    file: config/scenarios.yaml
  shared_cutouts: true
  shared_resources:
    policy: base

scenario:
  clusters:
  - 16
  sector_opts:
  - 3H
  # planning_horizons:
  # - 2050

countries: ['NL', 'BE', 'DE', 'NO', 'DK'] #, 'BE', 'DE', 'NO', 'DK', 'GB'

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"

enable:
  retrieve: true

electricity:
  powerplants_filter: (DateOut >= 2024 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear') and not (Name.str.contains("Borssele") and Fueltype == "Hard Coal")
  custom_powerplants: true
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT] #, geothermal, nuclear

sector:
  district_heating:
    ptes:
      dynamic_capacity: true
    # dh_area_buffer: 1000
    limited_heat_sources:
      geothermal:
        constant_temperature_celsius: 65
        ignore_missing_regions: true
  tes: true
  # ht_ates: false
  gas_network: true
  heat_pump_sources:
    urban central:
    - air
    - geothermal

enable:
  retrieve_cost_data: false
  build_cutout: false
  retrieve_cutout: true

# costs:
#   marginal_cost:
#     central HTATES charger: 0.035

clustering:
  focus_weights:
    NL: 0.75

solving:
  solver:
    name: gurobi
    options: gurobi-default
  solver_options:
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200

  mem_mb: 50000 #memory in MB
